version: 0.0
os: linux
files:
  - source: /tomcat/target/LoginWebApp-1.war
    destination: /opt/tomcat/webapps/

hooks:
  AfterInstall:
    - location: install.sh
      timeout: 300
      runas: root
